name: Autorelease

on:
  schedule:
    - cron: 0 20 * * 0
  workflow_dispatch:

jobs:
  release:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - run: echo LATEST_VERSION=$(git rev-list -n 1 $(git describe --abbrev=0 --tags))>> $GITHUB_ENV
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_ACTION_KEY }}
      - name: Calver Release
        uses: StephaneBour/actions-calver@master
        id: calver
        if: ${{ env.LATEST_VERSION != github.sha }}
        with:
          date_format: "%Y.%V"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
