name: Autorelease

on:
  schedule:
    - cron: 0 20 * * 0
  workflow_dispatch:

jobs:
  release:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_ACTION_KEY }}
      - name: Set Calver Version
        uses: Nelyx/action-calver@v1.0.0
        id: setcalver
        with:
          default_branch: 'refs/heads/master'
          format: 'YYYY.M'
          version_prefix: ''
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          draft: false
          prerelease: false
          tag_name: ${{ steps.setcalver.outputs.package_version }}
          generate_release_notes: true
          
